### ISSUE TITLE
move crosswalk files (prepended with "MASTER" to their own subdirectory "crosswalks".  see subtasks below

### ISSUE THREAD

**Issue by timbender-ncceh** [timbender-ncceh/ce_assessment#12]
- [ ] edit names of files to include new "crosswalk" subdirectory for each (i.e.  /some/dir/crosswalks/file1.csv)
- [ ] fix broken links in ce_assessment_micro2.R (and subsequent)
- [ ] fix broken links in exploratory_data_analysis2.R (and subsequent)
- [ ] fix broken links in ce_montecarlo_weights.R (and subsequent)
- [ ] fix broken links in ce_data_dity.R (and subsequent)
- [ ] fix broken links in README.md in GitHub. 
- [ ] be on the lookout for other broken links.
